sudo: 
  required

language: 
  c 

services:
  - docker

before_install:

  - sudo apt-get install -y debootstrap schroot

  # # copy config file
  - sudo cp srv/chroot/trusty_x86_64 /etc/schroot/chroot.d/trusty_x86_64
  # # create chroot
  - sudo debootstrap --variant=buildd --arch amd64 trusty /srv/chroot/trusty_x86_64
  # #enter chroot
  - schroot -c trusty_x86_64 -u travis -b
  # # install headers
  - sudo apt-get install -y linux-headers-3.19.0-28 linux-headers-3.19.0-30-generic # $(uname -r)

  # add VirtualBox repo, GPG keys, install and check
  - sudo echo deb "http://download.virtualbox.org/virtualbox/debian trusty contrib" | sudo tee -a /etc/apt/sources.list
  - wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install -y virtualbox-5.0
  - VBoxManage --version 

  - apt-get -f install ## fix dependencies (?)

  # where are the installed modules?
  - lsmod
  - find /lib/modules/`uname -r` -name '*.ko' 
  # - modprobe -l *
  - modinfo vboxdrv

  - ls -lsA /lib/modules/
  - pwd

  # let's try some random Vagrant box
  - sudo apt-get install vagrant
  - vagrant box add precise32 http://files.vagrantup.com/precise32.box
  - vagrant init
  - vagrant up




  # # # # update APT sources
  # - sudo echo deb "http://download.virtualbox.org/virtualbox/debian trusty contrib" | sudo tee -a /etc/apt/sources.list

  # - wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -

  # - sudo apt-get install -y dkms




script:
  # - make build ACCOUNT=$ACCOUNT
  - whoami